import java.time.Year;

/**
 * Demonstrates the "clean" approach to HashSet deduplication using a Java record.
 *
 * <p>{@code Song} is now a {@code record}: {@code equals}, {@code hashCode}, {@code toString},
 * and all accessors are generated by the compiler — zero boilerplate. The {@link SongsProcessor}
 * uses a factory method ({@code from}) and {@link java.util.Optional} for safe lookups.
 *
 * <p>Compare with {@code 0_hashset/SongsDemo.java} to see the difference.
 */
void main() {
    var processor = SongsProcessor.from("worst-songs.txt");

    IO.println("=== Stats ===");
    IO.println("Unique songs  : " + processor.countSongs());
    IO.println("Total artists : " + processor.countArtists());

    IO.println("\n=== Find by code (Optional) ===");
    processor.findByCode(1258)
             .ifPresentOrElse(
                 song -> IO.println("Found: " + song),
                 ()   -> IO.println("Song not found")
             );

    IO.println("\n=== Find by artist ===");
    processor.findByArtist("Barry Manilow")
             .forEach(IO::println);

    IO.println("\n=== Find by year ===");
    processor.findByYear(Year.of(1977))
             .forEach(IO::println);

    IO.println("\n=== Oldest songs ===");
    processor.findOldestSongs().forEach(IO::println);

    IO.println("\n=== Most recent songs ===");
    processor.findMostRecentSongs().forEach(IO::println);
}
